### PR TITLE
Allow user-defined ports (ESF-99)

### PR DESCRIPTION
**Pull request by higaski**
Don't force users of this library to pick one of the existing ports. Users may implement their own and still want to use CMake...

### CODE REVIEW

**Comment by higaski** [comment]
Now that I think about it...
I'd even go as far and say `USER_DEFINED` should be the default option and CMake should not throw a FATAL_ERROR at all if `PORT` isn't defined. A simple warning might be sufficient in this case?

**Comment by DNedic** [comment]
Hello @higaski , thank you for your contribution. If the user maintains their own fork of the library, with their port, isn't adding these 2 lines a trivial excercise by that point?

**Comment by higaski** [comment]
I'm not sure what you mean. This library explicitly supports adding a [new host target](https://github.com/espressif/esp-serial-flasher/tree/master#supporting-a-new-host-target) by implementing just 6x C functions. This currently does not work however because the CMakeLists.txt file forces one of the already existing hosts on the user.

**Comment by DNedic** [comment]
I am guessing you are reffering to the workflow where you implement the port in your project and then link it with the flasher library?

In that case yes, this would be useful and very convenient. 

Could you change your MR so it picks `USER_DEFINED` by default if `PORT` is not defined?

**Comment by DNedic** [comment]
It would be useful to be able to manually set `USER_DEFINED` to avoid the warning, but if nothig is set print the warning and set `USER_DEFINED`.

I will update the documentation later accordingly.

**Comment by higaski** [comment]
Ok so I've added the `USER_DEFINED` `PORT` option.
- If `PORT` is undefined it prints a warning and defaults to `USER_DEFINED`.
- Setting `PORT` to `USER_DEFINED` avoids a warning.
- Setting `PORT` to any unknown value still triggers an error.

With that out of the way I still have to criticize the CMakeLists.txt file in general. In my opinion the abundance of if-else statements make it very difficult to figure out what configurations actually get set. The main problem that probably led to this is that undefined variables are used as options instead of using sensible default values. The entire file could probably be 50 lines long if the "if not defined, then" pattern were not used so often. All those calls which conditionally add to some list (e.g. `target_compile_definitions`) could have been [generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html).

**Comment by DNedic** [comment]
Thanks for the contribution @higaski , I will update the documentation accordingly and reference `PORT` setting. 

Could you provide some examples of cleaning up the CMakeLists file? Also, we do accept contributions so if you think anything can be improved we are open to merging it.

**Comment by higaski** [comment]
I just realized that not only is the current CMakeLists.txt file hard to read, it also doesn't work for all options. Take a look at the way `SERIAL_FLASHER_RESET_HOLD_TIME_MS` and `SERIAL_FLASHER_BOOT_HOLD_TIME_MS` currently gets set when building for non ESP platforms.

```cmake
if(NOT DEFINED SERIAL_FLASHER_RESET_HOLD_TIME_MS)
    target_compile_definitions(${target}
    PUBLIC
        SERIAL_FLASHER_RESET_HOLD_TIME_MS=100
    )
endif()
```

Once this option gets set by the user it no longer makes it way to the C compiler.
```sh
# Let CMake pick the default option
cmake -Bbuild -GNinja
[1/7] /usr/bin/cc -DSERIAL_FLASHER_BOOT_HOLD_TIME_MS=50 -DSERIAL_FLASHER_INTERFACE_UART -DSERIAL_FLASHER_RESET_HOLD_TIME_MS=100 -DSERIAL_FLASHER_WRITE_BLOCK_RETRIES=3
```

```sh
# Try to override the option
cmake -Bbuild -GNinja -DSERIAL_FLASHER_RESET_HOLD_TIME_MS=200
[1/7] /usr/bin/cc -DSERIAL_FLASHER_BOOT_HOLD_TIME_MS=50 -DSERIAL_FLASHER_INTERFACE_UART -DSERIAL_FLASHER_WRITE_BLOCK_RETRIES=3
# -DSERIAL_FLASHER_RESET_HOLD_TIME_MS=200 missing
```

<br>  
<br>

I was probably a little too cheeky before, I just realized that you guys need to deal with all the KConfig options as well which of course makes things a little bit trickier. Also note that I'm not a CMake expert either.... Any how, I'd probably start with gathering all options in a single  place. Well... or at least two places, because on ESP all CMake options will be set from Kconfig. Sadly [set](https://cmake.org/cmake/help/latest/command/set.html) does not support generator expressions so we can't avoid an if here.

```cmake
if (ESP_PLATFORM)
  set(SERIAL_FLASHER_RESET_HOLD_TIME_MS
      ${CONFIG_SERIAL_FLASHER_RESET_HOLD_TIME_MS}
      CACHE STRING "Time for which the boot pin is asserted when doing a hard reset"
  )
  # More options here...
else()
  set(SERIAL_FLASHER_RESET_HOLD_TIME_MS
      50
      CACHE STRING "Time for which the boot pin is asserted when doing a hard reset"
  )
  # More options here...
endif()
```

After that we'd no longer have to deal with all the `CONFIG_*` variables. Adding all definitions becomes a single call to
```cmake
target_compile_definitions(${target} PUBLIC 
  # Just add all definitions
  SERIAL_FLASHER_RESET_HOLD_TIME_MS=${SERIAL_FLASHER_RESET_HOLD_TIME_MS}
  SERIAL_FLASHER_WRITE_BLOCK_RETRIES=${SERIAL_FLASHER_WRITE_BLOCK_RETRIES}
  # or some only conditionally
  $<${MD5_ENABLED}:MD5_ENABLED>
)
```

Similar simplifications could be done for the sources. E.g., adding UART or SPI source might look something like this
```cmake
target_sources(${target} 
  $<${SERIAL_FLASHER_INTERFACE_UART}:src/protocol_uart.c>
  $<${SERIAL_FLASHER_INTERFACE_SPI}:src/protocol_spi.c>
  # Might need conversion to bool? Not sure about that...
  $<$<BOOL:${SERIAL_FLASHER_INTERFACE_UART}>:src/protocol_uart.c>
)
```

Those `SERIAL_FLASHER_INTERFACE_*` configurations should probably be 1 variable, not 2...
```cmake
set(SERIAL_FLASHER_INTERFACE "UART"
    CACHE STRING "Serial flasher interface could be either UART or SPI"
)
```
but that might be a breaking change, not sure if that's worth it.

**Comment by DNedic** [comment]
> I just realized that not only is the current CMakeLists.txt file hard to read, it also doesn't work for all options. Take a look at the way SERIAL_FLASHER_RESET_HOLD_TIME_MS and SERIAL_FLASHER_BOOT_HOLD_TIME_MS currently gets set when building for non ESP platforms.

Thanks for notifying us, I have actually just found this issue last night but didn't get the MR reviewed yet.

> I was probably a little too cheeky before, I just realized that you guys need to deal with all the KConfig options as well which of course makes things a little bit trickier. Also note that I'm not a CMake expert either.... Anyhow, I'd probably start with gathering all options in a single place. Well... or at least two places, because on ESP all CMake options will be set from Kconfig. Sadly [set](https://cmake.org/cmake/help/latest/command/set.html) does not support generator expressions so we can't avoid an if here.

While it does sound like a great idea at first, to be honest I don't think it's the best choice. Reasoning being, when an option is added, it is much easier to forget to add handling for it in 2 places than 1, and the pattern for checking whether the `Kconfig` variant has been set is quite easy to remember.

> Similar simplifications could be done for the sources. E.g., adding UART or SPI source might look something like this
> ```cmake
> target_sources(${target} 
>   $<$<BOOL:${SERIAL_FLASHER_INTERFACE_UART}>:src/protocol_uart.c>
>   $<$<BOOL:${SERIAL_FLASHER_INTERFACE_SPI}>:src/protocol_spi.c>
> )
> ```

The problem with this code is that those 2 options are not mutually exclusive.

> Those SERIAL_FLASHER_INTERFACE_* configurations should probably be 1 variable, not 2...
> ```cmake
> set(SERIAL_FLASHER_INTERFACE "UART"
>     CACHE STRING "Serial flasher interface could be either UART or SPI"
> )
> ```

We will consider this, thanks for the suggestion.

**Pull request merged**
